Repository fire-ferrets/cipy, pull requests merged in 2018-08, with the labels that each got.

#3 Add empty morse.py module
  cipy/ciphers/morse.py
Labels: WIP

#4 Add empty rail_fence.py
  cipy/ciphers/rail_fence.py
Labels: WIP

#7 Improve morse symbol replacement
  cipy/ciphers/morse.py
Labels: enhancement

#8 Add empty vigenere.py
  cipy/ciphers/vigenere.py
Labels: WIP

#5 Add Alphabet class
  cipy/alphabet/__init__.py
  cipy/alphabet/alphabet.py
Labels: WIP, enhancement

#13 Add testing suite and fix errors
  cipy/__init__.py
  cipy/ciphers/__init__.py
  cipy/ciphers/a1z26.py
  cipy/ciphers/francis_bacon.py
  cipy/ciphers/rot.py
  setup.py
  tests/__init__.py
  tests/ciphers/__init__.py
  tests/ciphers/test_a1z26.py
  tests/ciphers/test_ascii.py
  tests/ciphers/test_atbash.py
  tests/ciphers/test_francis_bacon.py
  tests/ciphers/test_morse.py
  tests/ciphers/test_rail_fence.py
  tests/ciphers/test_rot.py
  tests/ciphers/test_vigenere.py
Labels: enhancement, testing

#15 Unify names and update docstring
  cipy/ciphers/a1z26.py
  cipy/ciphers/ascii.py
  cipy/ciphers/atbash.py
  cipy/ciphers/francis_bacon.py
  cipy/ciphers/morse.py
  cipy/ciphers/rail_fence.py
  cipy/ciphers/rot.py
  cipy/ciphers/vigenere.py
Labels: WIP, documentation, enhancement

#17 imported alphabet class
  cipy/__init__.py
  cipy/alphabet/__init__.py
  cipy/ciphers/a1z26.py
Labels: WIP, bug
